### ISSUE TITLE
Plugin configuration issues

### ISSUE THREAD

**Issue by reshmabidikar** [killbill/killbill-avatax-ui#4]
## Upload plugin configuration does not work

1. Click on the plug icon -> Avatax
2. Click on `Plugin Configuration`
3. Enter valid values for `Account ID` and `License key`
4. This displays a "We're sorry, but something went wrong." message. 

The following error is displayed in the logs:

```
2023-02-07T06:53:28,302+0000 lvl='INFO', log='rack', th='http-nio-9090-exec-10', xff='', rId='d2ea126c-f9aa-429d-9b0b-be27d6c64f8c', tok='', aRId='', tRId='',F, [2023-02-07T06:53:28.302000 #10456] FATAL -- : org/jruby/RubyString.java:2274:in `concat'
gems/gems/killbill-avatax-2.1.0/app/controllers/avatax/configuration_controller.rb:100:in `update_plugin_configuration'
gems/gems/actionpack-5.1.0/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
gems/gems/actionpack-5.1.0/lib/abstract_controller/base.rb:186:in `process_action'
gems/gems/actionpack-5.1.0/lib/action_controller/metal/rendering.rb:30:in `process_action'
gems/gems/actionpack-5.1.0/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
gems/gems/activesupport-5.1.0/lib/active_support/callbacks.rb:131:in `run_callbacks'
gems/gems/actionpack-5.1.0/lib/abstract_controller/callbacks.rb:19:in `process_action'
gems/gems/actionpack-5.1.0/lib/action_controller/metal/rescue.rb:20:in `process_action'
gems/gems/actionpack-5.1.0/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
gems/gems/activesupport-5.1.0/lib/active_support/notifications.rb:166:in `block in instrument'
gems/gems/activesupport-5.1.0/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
gems/gems/activesupport-5.1.0/lib/active_support/notifications.rb:166:in `instrument'
gems/gems/actionpack-5.1.0/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
gems/gems/actionpack-5.1.0/lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
gems/gems/activerecord-5.1.0/lib/active_record/railties/controller_runtime.rb:22:in `process_action'
gems/gems/actionpack-5.1.0/lib/abstract_controller/base.rb:124:in `process'
gems/gems/actionview-5.1.0/lib/action_view/rendering.rb:30:in `process'
gems/gems/actionpack-5.1.0/lib/action_controller/metal.rb:189:in `dispatch'
gems/gems/actionpack-5.1.0/lib/action_controller/metal.rb:253:in `dispatch'
gems/gems/actionpack-5.1.0/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
gems/gems/actionpack-5.1.0/lib/action_dispatch/routing/route_set.rb:31:in `serve'
gems/gems/actionpack-5.1.0/lib/action_dispatch/journey/router.rb:46:in `block in serve'
org/jruby/RubyArray.java:1735:in `each'
gems/gems/actionpack-5.1.0/lib/action_dispatch/journey/router.rb:33:in `serve'
gems/gems/actionpack-5.1.0/lib/action_dispatch/routing/route_set.rb:832:in `call'
gems/gems/railties-5.1.0/lib/rails/engine.rb:522:in `call'
org/jruby/RubyKernel.java:1830:in `public_send'
gems/gems/railties-5.1.0/lib/rails/railtie.rb:185:in `method_missing'
gems/gems/actionpack-5.1.0/lib/action_dispatch/routing/mapper.rb:17:in `block in Constraints'
gems/gems/actionpack-5.1.0/lib/action_dispatch/routing/mapper.rb:46:in `serve'
gems/gems/actionpack-5.1.0/lib/action_dispatch/journey/router.rb:46:in `block in serve'
org/jruby/RubyArray.java:1735:in `each'
gems/gems/actionpack-5.1.0/lib/action_dispatch/journey/router.rb:33:in `serve'
gems/gems/actionpack-5.1.0/lib/action_dispatch/routing/route_set.rb:832:in `call'
gems/gems/warden-1.2.9/lib/warden/manager.rb:36:in `block in call'
org/jruby/RubyKernel.java:1138:in `catch'
gems/gems/warden-1.2.9/lib/warden/manager.rb:34:in `call'
gems/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
gems/gems/rack-2.2.3/lib/rack/conditional_get.rb:40:in `call'
gems/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
gems/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
gems/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
gems/gems/actionpack-5.1.0/lib/action_dispatch/middleware/cookies.rb:613:in `call'
gems/gems/actionpack-5.1.0/lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
gems/gems/activesupport-5.1.0/lib/active_support/callbacks.rb:97:in `run_callbacks'
gems/gems/actionpack-5.1.0/lib/action_dispatch/middleware/callbacks.rb:24:in `call'
gems/gems/actionpack-5.1.0/lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
gems/gems/actionpack-5.1.0/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
gems/gems/railties-5.1.0/lib/rails/rack/logger.rb:36:in `call_app'
gems/gems/railties-5.1.0/lib/rails/rack/logger.rb:24:in `block in call'
gems/gems/activesupport-5.1.0/lib/active_support/tagged_logging.rb:69:in `block in tagged'
gems/gems/activesupport-5.1.0/lib/active_support/tagged_logging.rb:26:in `tagged'
gems/gems/activesupport-5.1.0/lib/active_support/tagged_logging.rb:69:in `tagged'
gems/gems/railties-5.1.0/lib/rails/rack/logger.rb:24:in `call'
gems/gems/actionpack-5.1.0/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
gems/gems/actionpack-5.1.0/lib/action_dispatch/middleware/request_id.rb:25:in `call'
gems/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
gems/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
gems/gems/activesupport-5.1.0/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
gems/gems/actionpack-5.1.0/lib/action_dispatch/middleware/executor.rb:12:in `call'
gems/gems/actionpack-5.1.0/lib/action_dispatch/middleware/static.rb:125:in `call'
gems/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
gems/gems/railties-5.1.0/lib/rails/engine.rb:522:in `call'
uri:classloader:/rack/handler/servlet.rb:22:in `call'
```

## UI Improvements
1. The UI needs to be updated to accept other configuration properties as documented [here](https://github.com/killbill/killbill-avatax-plugin#avalara-avatax). At the very least, it should at least accept values for the `org.killbill.billing.plugin.avatax.url`/`org.killbill.billing.plugin.avatax.taxratesapi.url` properties
2. If some properties are not mandatory, this should be indicated in the UI and their default values should be pre-populated
3. The UI should provide a brief explanation for each property (Maybe when the mouse is moved over the property name?)

**Comment by tungleduyxyz** [comment]
Hi @reshmabidikar , 
I made a PR here: https://github.com/killbill/killbill-avatax-ui/pull/13
Please help me to verify this.
To test this, you must create a new tenant, and test with a new tenant because this issue only happens when the tenant doesn't have any AvataxConfiguration.
